# https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx
  version: v4.2.5
  set:
  valuesContent: |-
    fullnameOverride: ingress-nginx
    controller:
      kind: DaemonSet
      hostNetwork: false
      hostPort:
        enabled: false
      resources:
        limits:
          cpu: 1500m
          memory: 1200Mi
        requests:
          cpu: 200m
          memory: 200Mi
      service:
        enabled: true
        nodePorts:
          http: 32080 
          https: 32443
      publishService:
        enabled: false
      config:
        use-forwarded-headers: "true"
        proxy-body-size: "500m"
        proxy-buffer-size: "32k"
