apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: infra+ws@zcloud.ws
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: zcloud-ws-letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx
